openapi: 3.1.1
info:
  title: Dialektor Backend
  description: |-
    This is the API interface for the Dialektor project

  license:
    name: GNU GPL
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 0.1.0

servers:
  - url: http://localhost:3000
    description: Local server

tags:
  - name: General
    description: Miscellaneous Endpoints
  - name: Countries
    description: Operations relating to country data
  - name: Scripts
    description: Operations relating to script data
  - name: Languages
    description: Operations relating to language data

paths:
  /version:
    get:
      tags:
      - General
      summary: Gets the current service version
      description: Retrieves the version of the service and returns it
      operationId: getVersion
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                required:
                    - version
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /countries:
    get:
      tags:
      - Countries
      summary: Get all countries
      description: Get all countries in the database
      operationId: getCountries
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Country'
                example:
                  - id: '7eeddda4-afbb-4bc8-bae0-82b514a9c636'
                    name: 'Albania'
                  - id: '7f5f295d-06f4-4e79-a709-5f93845cf8ec'
                    name: 'Kosova'
                  - id: 'dfca8f48-d8e6-4d8e-beac-5d98887ef238'
                    name: 'North Macedonia'
                  - id: '64edfb91-418d-4364-b93d-1fadaf331a4c'
                    name: 'Montenegro'
                  - id: '8a39f1e8-bba8-495d-b36d-3dcbb4bd4f70'
                    name: 'Greece'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      tags:
      - Countries
      summary: Create a country
      description: Create a country
      operationId: createCountry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
        '400':
          description: Bad Request - Missing country name in body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /countries/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
    get:
      tags:
      - Countries
      summary: Get a country
      description: Get the country with the given ID
      operationId: getCountry
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
        '404':
          description: Country not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    patch:
      tags:
        - Countries
      summary: Update a country
      description: Update the country with the given ID
      operationId: updateCountry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
        '404':
          description: Country not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      tags:
        - Countries
      summary: Delete a country
      description: Delete the country with the given ID
      operationId: deleteCountry
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
  /scripts:
    get:
      tags:
        - Scripts
      summary: Get all scripts
      description: Get all scripts
      operationId: getScripts
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Script'
                example:
                  - name: 'LATIN'
                  - name: 'CYRILLIC'
    post:
      tags:
        - Scripts
      summary: Create a new script
      description: Create a new script
      operationId: createScript
      requestBody:
        required: true
        content:
          application/json:
            schema:
                  $ref: '#/components/schemas/Script'
      responses:
          '200':
            description: Successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Script'
          '400':
            description: Bad Request - Missing script name in body
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
  /scripts/{name}:
    parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
    delete:
      tags:
        - Scripts
      summary: Delete a script
      description: Delete a script
      responses:
          '200':
            description: Successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Script'
  /languages:
    get:
      tags:
        - Languages
      summary: Get all languages
      description: Get all languages in the system
      operationId: getLanguages
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Language'
                example:
                    - id: '8d8798a0-b21b-47ec-867e-9960a1afc20a'
                      name: 'Albanian'
                      script: 'LATIN'
                    - id: '02f3f531-667f-4f65-96ce-4db62a3f2f5c'
                      name: 'Turkish'
                      script: 'LATIN'
                    - id: 'a82fbe46-90f4-4e2e-9667-b0b9d9609467'
                      name: 'Macedonian'
                      script: 'CYRILLIC'
    post:
      tags:
        - Languages
      summary: Create a new language
      description: Create a new language
      operationId: createLanguage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: 
                  type: string
                  example: Albanian
                script:
                  type: string
                  example: LATIN
              required:
                - name
                - script
      responses:
          '200':
            description: Successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Language'
          '400':
            description: Bad Request - Missing script or name in body
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
  /languages/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
    get:
      tags:
        - Languages
      summary: Get a Language
      description: Get the language associated with the given ID
      operationId: getLanguage
      responses:
          '200':
            description: Successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Language'
          '400':
            description: Bad Request - Invalid UUID
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
    patch:
      tags:
        - Languages
      summary: Update a language
      description: Update the language associated with the ID
      operationId: updateLanguage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: 
                  type: string
                  example: Albanian
                script:
                  type: string
                  example: LATIN
      responses:
          '200':
            description: Successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Language'
          '400':
            description: Bad Request - Invalid UUID
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'


components:
  schemas:
    Country:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: '8d8798a0-b21b-47ec-867e-9960a1afc20a'
        name:
          type: string
          example: 'Albania'
      required:
        - id
        - name
    Script:
      type: object
      properties:
          name:
            type: string
            example: 'LATIN'
      required:
          - name
    Language:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: '8d8798a0-b21b-47ec-867e-9960a1afc20a'
        name:
          type: string
          example: 'Albanian'
        script:
          type: string
          example: 'LATIN'
    Error:
      type: object
      properties:
        error:
          type: string
      required:
        - error
